### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by topiasukkonen** [samusyrjanen/sortext#1]
19.30 14th June 2023
The project is overall in good shape. It already has extensive and detailed documentation. On my laptop the project seemed to work as expected. User interface is extensive and has a lot of details on how to use the program. Making the UI a bit more simple could maybe enhance usability, but also that would cause diminishing of the thoroughness of the program, so it might be just fine the way it is at the moment. On the code level, it was easy to follow what each function etc. is responsible for as variable names are proper. I think the project is great and the idea has been successfully implemented. Just add a release to this project once it is ready. Great job!

**Comment by samusyrjanen** [comment]
Thanks
